
// Workflow types for the marketplace
export const workflowTypes = [
  {
    id: "la-utility-trenching",
    title: "LA County Utility Trenching Permit Workflow",
    description: "Complete workflow for utility trenching permits in Los Angeles County.",
    agency: "LA County Public Works",
    permitType: "utility",
    rating: 4.8,
    reviews: 24,
    price: 299,
    verified: true,
  },
  {
    id: "la-traffic-control",
    title: "LA County Traffic Control Plan Package",
    description: "Traffic control plan templates and automated permit generation for LA County.",
    agency: "LA Department of Transportation",
    permitType: "traffic",
    rating: 4.6,
    reviews: 18,
    price: 249,
    verified: true,
  },
  {
    id: "la-sidewalk",
    title: "LA County Sidewalk Construction Workflow",
    description: "Step-by-step workflow for sidewalk construction permits in LA County.",
    agency: "LA County Public Works",
    permitType: "sidewalk",
    rating: 4.5,
    reviews: 12,
    price: 199,
    verified: true,
  },
  {
    id: "la-road-repair",
    title: "LA County Road Repair & ROW Permits",
    description: "Comprehensive workflow for road repair and right-of-way permits in LA County.",
    agency: "LA County Public Works",
    permitType: "road",
    rating: 4.7,
    reviews: 15,
    price: 279,
    verified: false,
  },
  {
    id: "la-storm-drain",
    title: "LA County Storm Drain Installation Package",
    description: "Complete permit workflow for storm drain installations in LA County.",
    agency: "LA County Flood Control District",
    permitType: "utility",
    rating: 4.4,
    reviews: 9,
    price: 229,
    verified: false,
  },
];
