
project_id = "soqkdzjefmprswahhtsp"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions]
[functions.create-checkout]
verify_jwt = true
