// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://soqkdzjefmprswahhtsp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvcWtkemplZm1wcnN3YWhodHNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2OTEwMDgsImV4cCI6MjA1OTI2NzAwOH0.YP8QinSzQilv0jXUAZXcTKWqq7-jCp6VftC_fixL4TU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);